FROM jupyter/minimal-notebook:latest

# install apptainer or docker


# install ngshare stuff
COPY nbgrader_config.py /etc/jupyter/nbgrader_config.py
RUN python3 -m pip install ngshare_exchange

# install ewatercycle + its deps

# install extra jupyter extensions like lsp